"""Domain models and community context for Elbysodic."""

from elbysodic.domain.boards import (
    BOARD_KINDS,
    BOARD_SIDEBAR_SECTIONS,
    DEFAULT_SIDEBAR_SECTION_CONFIGS,
    BoardKind,
    BoardSidebarSection,
    SidebarRealm,
    is_community_board,
    is_community_sidebar_board,
    is_desk_board,
    is_desk_sidebar_board,
    is_location_board,
    is_location_sidebar_board,
    is_studio_sidebar_board,
    normalize_board_kind,
    normalize_board_sidebar_section,
)
from elbysodic.domain.context import DEFAULT_COMMUNITY_ID, CommunityContext
from elbysodic.domain.models import (
    Board,
    Character,
    Community,
    CommunityMembership,
    Notification,
    Post,
    Role,
    SidebarSectionConfig,
    Thread,
    ThreadParticipant,
    ThreadWatch,
    User,
)

__all__ = [
    "BOARD_KINDS",
    "BOARD_SIDEBAR_SECTIONS",
    "DEFAULT_COMMUNITY_ID",
    "DEFAULT_SIDEBAR_SECTION_CONFIGS",
    "Board",
    "BoardKind",
    "BoardSidebarSection",
    "Character",
    "Community",
    "CommunityContext",
    "CommunityMembership",
    "Notification",
    "Post",
    "Role",
    "SidebarRealm",
    "SidebarSectionConfig",
    "Thread",
    "ThreadParticipant",
    "ThreadWatch",
    "User",
    "is_community_board",
    "is_community_sidebar_board",
    "is_desk_board",
    "is_desk_sidebar_board",
    "is_location_board",
    "is_location_sidebar_board",
    "is_studio_sidebar_board",
    "normalize_board_kind",
    "normalize_board_sidebar_section",
]
